### ISSUE TITLE
authentication for EFM projects

### ISSUE THREAD

**Issue by mujakob** [sed-group/sed-backend#14]
right now all routes are "open to public"
specific projects need specific authentication (maybe add a field "user group" to the project?) which manages access
maybe the entire EF-M needs it's own authentication table?
these and many more interesting design decisions are waiting for you to solve them!

**Comment by johnmartins** [comment]
No time allocated into implementation of EF-M into SED labs in the past year. Currently seems unlikely to be implemented as was originally envisioned. Cancelling issue.
