### ISSUE TITLE
Subprojects cannot be deleted if created without a project

### ISSUE THREAD

**Issue by EppChops** [sed-group/sed-backend#92]
**Describe the bug**
As of now it is possible from the implementation interface of the core/project module to create subprojects without having a project connected to them. 

It is however impossible to remove those subprojects, or access them from the router level, if they are not connected to a project. 

I ran into the issue when creating a subproject for testing purposes and then wanted pytest to automatically remove it but instead it caused an error within the "impl_delete_subproject()" method. 

**To Reproduce**
1. Create a subproject without a project present
2. Try to delete or view it from the API

**Expected behavior**
Not really sure, @johnmartins should know. Either allow to remove subprojects when "project" is None, or force the use of projects on subprojects?

**Screenshots**
Error messages in terminal from pytest: 
![Screenshot_2023-05-30_18-27-29](https://github.com/sed-group/sed-backend/assets/57296415/74a08826-ad99-4102-b5a9-71145f2a91db)
![Screenshot_2023-05-30_18-27-37](https://github.com/sed-group/sed-backend/assets/57296415/f6d0f84b-28a0-467e-865a-aff31405dd22)

The code in question:
![Screenshot_2023-05-30_18-23-13](https://github.com/sed-group/sed-backend/assets/57296415/aeb6e394-e6e8-4216-8a25-57849d828c2a)

**Desktop (please complete the following information):**
 - OS: Linux (docker container)
 - Browser: N/A

**Comment by johnmartins** [comment]
Thanks for pointing this out, it is indeed not possible in the current version.

However, in version 1.0.4 (#87) it is possible to access subprojects from the router layer using appID and subprojectID. I will also add a solution for removing them without a project.

**Comment by johnmartins** [comment]
Resolved in v.1.0.4
